### PR TITLE
Automatically build fonts in github-actions CI with FontCustom

### LINKED ISSUE #109: Distributing work of adding icons via PR?
Right now, the process for adding new icons is to create an issue and submit an SVG of the requested glyph and wait to see whether @jpswalsh wants to add it when he has time in his busy life.

Is there a way this project could be adapted to allow users to do more of the work ourselves: convert the SVG into the appropriate format to add to the `.eot`, `.ttf`, `.svg`, and `.woff` font files, and then submit a PR, as opposed to needing one person to do all the work alone?

For instance, I'd be willing to do work to speed up adding the SSRN logo (#42) and The Conversation (#56) to academicicons if there were a clear process for doing so.

Part of the challenge is that git is not good at merging different versions of binary files like `academicicons.ttf`, so a process like this would only work well if there were a toolchain to automate building the main font files `(academicicons.ttf`, `.eot`, `.svg`, and `.woff`) from .svg files for the individual glyphs (or from a master `.svg` for the whole font, since that's a textual XML-based format), and adapting this project to that way of working might be a lot more trouble than it's worth.

### PR DESCRIPTION
**Pull request by lucjaulmes**
Fixes #109.
Fork-Awesome uses [FontCustom](https://github.com/FontCustom/fontcustom) to build their fonts. This PR allows doing the same with academicons.

- On every commit, the following files are built:
  ```
  academicons-preview.html
  css/academicons.css
  css/academicons.min.css
  fonts/academicons.eot
  fonts/academicons.svg
  fonts/academicons.ttf
  fonts/academicons.woff
  fonts/academicons.woff2
  ```
  That is, the same organization of files as the current repo, with an additional preview file.

  All these files are uploaded in a single `academicons.zip` archive downloadable from the “artifacts” drop-down menu of the github actions.  
  artifcats menu screenshot

- Visual inspection of fonts is possible by extracting the archive and opening `academicons-preview.html`

- PRs only need to add an svg file to the svg/ directory with the desired basename. Fonts are automatically built, see for example the test PR lucjaulmes/academicons#1 which triggered the build:
  https://github.com/lucjaulmes/academicons/pull/1/checks?check_run_id=2527748877

  Adding `erc.svg` correctly adds a `.ai-erc` icon.  Opening the preview file from the artifacts confirms my ERC icon from #105 looks terrible :)
  
  ERC icon preview

I’m not sure whether keeping the css and fonts in the source code remains useful after this PR ?

### CODE REVIEW

**Review by nfrerebeau — COMMENTED** [review]
It looks pretty cool!

At first glance there are a few problems though:

* Some settings need to be changed to match the current font properties:
```
font_design_size: 16
font_em: 512
font_ascent: 448
font_descent: 64
```
* Many projects use academicons through the jsdelivr CDN which distributes the repository content. Instead of downloading the artifacts, the output of FontCustom should be deployed to the master branch after inspection. Artifacts are retained for 90 days before they are automatically deleted.
* FontCustom's character encoding is different from the [current encoding](https://jpswalsh.github.io/academicons/unicode) (e.g. Academia: \f100 vs \e9af). Maybe this can be defined in the FontCustom settings (at least so that the existing icons keep the same encoding)?

The first two items are easy to fix, but I have no clue for the third.

**Comment by lucjaulmes** [comment]
Updated the codepoints. It’s not the most user-friendly system to modify the (hidden) json manifest manually, so I made a `config/codepoints.json` that defines the codepoints and that automatically generates the manifest correctly.

I think (under your control @nfrerebeau) that that handles generating the fonts correctly. Easiest way to test that would be to generate that table again, but I’m unsure how to do that. We can further tweak css generation with templates.

Before looking at how this could be deployed, I think the next question should be what tests to include ?
- It would make sense on PRs to check that added codepoints are in the correct range.
- Not sure how to test “visually” that the font generation went well ?

**Comment by lucjaulmes** [comment]
Here’s some jsqdelivr-compatible progress on this. As jsdelivr always sends out the `master` branch even it is not the github default branch, I have setup 2 branches (on my repo):
- [master](https://github.com/lucjaulmes/academicons/tree/master), which contains the built fonts, css, docs, etc.
- [sources](https://github.com/lucjaulmes/academicons), now the main branch, which contains the sources and svg files

On every push and PR to `sources`, fonts, css, and docs are re-built. The glyphs are svg files from the svg/ directory, whose codepoints are listed on `config/codepoints.json`. The CI checks codepoints and glyph names. There is some visual testing, done be generating [a screenshot of a glyphs table](https://github.com/lucjaulmes/academicons/blob/master/test/glyph-table.png).

- On pushes, the built elements are deployed, i.e. pushed to master. Currently visual testing does not cause the CI to fail. A maximum number of changed pixels could be decided. (There is already some fuzzing etc. done by ImageMagick to compare properly, each glyph takes up to 2025 pixels.)
- On PRs, the diff is automatically posted to the thread [as with this example.](https://github.com/lucjaulmes/academicons/pull/1#issuecomment-835835178) This is done using a gist to store images. That way PRs can see if the modified changes are as planned, whether the changes break building fonts or not, etc.

The organization of files is the same than in master currently, so no changes for the docs and jsdelivr files.

----

To import this structure, the `sources` branch should be added to the repo and made the main branch, with some env keys modified in the workflow file:
- personal access token that has repo/gist/workflow rights for the TOKEN keys
- a gist URL on which the token has rights for the `GIST_URL` key

**Comment by nfrerebeau** [comment]
I will look at all this in the next few days.

**Comment by lucjaulmes** [comment]
This last commit comes from the fact I added a final (I think) feature:
- automatic deployment is not done when there are too many pixels changed at once. This allows to prevent deploying breaking changes.
- If there is ever a need for a push where lots of pixels change and it is normal (lots of icons updated, different browser used to render the screenshot, something like that), there is now a way to manually trigger the workflow with a 'force' flag to force ignore the pixel diff count

**Review by nfrerebeau — COMMENTED** [review]
Sorry for the late reply. The workflow seems OK, but there is an issue with the glyph generation. 

If `auto_width` is `false`, all glyphs are square and not centered. If `auto_width` is `true`, the glyph width is adjusted to the width of the svg path with a maximum width of 512px:

* We must be able to keep this white space for aesthetic reasons (we cannot rely on a CSS trick due to non-web uses of the font).
* Icons larger than 512px are scaled back (e.g. Zenodo): the baseline is moved and the overall consistency of the font is lost.

Unfortunately this seems to be a limitation of FontCustom: FontCustom/fontcustom#323... Also FontCustom seems to be unmaintained (but this may not be an immediate problem).

**Comment by lucjaulmes** [comment]
Sorry, I fail to see how the generated fonts are different form what we have today when `audo_width=false`. I used tested the differences between the fonts without use the generated css files nor the svg fonts. I fetched the fonts from `https://cdn.jsdelivr.net/gh/jpswalsh/academicons/fonts/` under the name `academicons-legacy` and  the fonts from `https://cdn.jsdelivr.net/gh/lucjaulmes/academicons/fonts/` under the name `academicons-fontforge`, and displayed them side-by-side by using the codepoints in HTML, and not the CSS classes (so definitely using fonts and not CSS images). I’ve also padded with underscores to visualize the baseline.

Both fonts look identical to me:
image

Some glyphs are wider than ohers, e.g. zenodo, but it’s the same in both fonts. You can see the ACM and all square fonts correctly dip below the baseline.

Here’s the file used to generate this image (gzipped to allow upload): [diff.html.gz](https://github.com/jpswalsh/academicons/files/6647142/diff.html.gz)

**Comment by nfrerebeau** [comment]
My bad, I manually inspected the fonts with FontForge and it seems to be related to the import in FontForge.

**Comment by lucjaulmes** [comment]
So this works right? Is there anything else you’d like included/changed?

**Pull request closed without merging**
